package:
  name: gaqet
  version: "1.16.4"

source:
  git_url: https://github.com/victorgcb1987/GAQET2.git
  git_tag: main

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python ==3.10.0
    - pip
  run:
    - python ==3.10.0
    - biopython
    - pandas
    - numpy
    - scipy
    - matplotlib-base
    - seaborn
    - pyyaml
    - blast >=2.12
    - agat ==1.5.1
    - psauron ==1.1.0
    - diamond ==2.1.13
    - busco ==6.0.0
    - ete3
    - dendropy
    - augustus ==3.5.0
    - samtools ==1.22.1
    - seqtk ==1.5
    - gffread ==0.12.7
    - omark ==0.3.1
    - tesorter ==1.4.7

about:
  home: https://github.com/victorgcb1987/GAQET2
  summary: "Genome Annotation Quality Evaluation Tool (GAQET2)"
  license: MIT
  license_file: LICENSE
