package:
  name: gaqet
  version: "1.13.18"

source:
  git_url: https://github.com/victorgcb1987/GAQET2.git
  git_tag: main

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python ==3.10.0
    - pip
  run:
    - python ==3.10.0
    - biopython
    - pandas
    - numpy
    - scipy
    - matplotlib-base
    - seaborn
    - pyyaml
    - blast >=2.12
    - agat
    - psauron 
    - diamond
    - busco
    - ete3
    - dendropy
    - augustus
    - samtools
    - seqtk
    - gffread
    - omark
    - tesorter

about:
  home: https://github.com/victorgcb1987/GAQET2
  summary: "Genome Annotation Quality Evaluation Tool (GAQET2)"
  license: MIT
  license_file: LICENSE
